topics:
- name    : joy
  topic   : joy_teleop/cmd_vel
  timeout : 2.0
  priority: 10
- name    : interactive_marker
  topic   : twist_marker_server/cmd_vel
  timeout : 0.5
  priority: 8
- name    : external
  topic   : cmd_vel
  timeout : 0.5
  priority: 4
- name    : RL_Env
  topic   : RLEnv/cmd_vel
  timeout : 2.0
  priority: 3
locks:
- name    : e_stop
  topic   : e_stop
  timeout : 0.0
  priority: 255
